version: '3.8'

services:
  # Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinbase_crypto_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=base64:a1VxJkAS03rUbwc7cY52gVuGXYlLqF+y3cKJORToGSA=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=coinbase_crypto
      - DB_USERNAME=root
      - DB_PASSWORD=1234
    depends_on:
      - db
    networks:
      - laravel

  # MySQL Database Service
  db:
    image: mysql:8.0
    container_name: coinbase_crypto_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: coinbase_crypto
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Nginx Web Server Service
  nginx:
    image: nginx:alpine
    container_name: Coinbase_crypto_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

# Volumes for persistent storage
volumes:
  dbdata:

# Networks to link containers
networks:
  laravel:
    driver: bridge
